version: '3.8'

services:
  downloadable_plugin:
    build: .
    container_name: downloadable_plugin
    # QUITAMOS LOS PORTS: - "8002:8000"
    networks:
      - odoo_network
    labels:
      - "traefik.enable=true"
      # Definimos la ruta de entrada para este plugin
      - "traefik.http.routers.downloadable_plugin.rule=PathPrefix(`/api/module1`)"
      - "traefik.http.routers.downloadable_plugin.entrypoints=web"
      # Le decimos a Traefik en qué puerto interno escucha FastAPI
      - "traefik.http.services.downloadable_plugin.loadbalancer.server.port=8000"
networks:
  odoo_network:
    external: true # IMPORTANTE: Le dice que use la red que ya creó el Kernel
